name = "weekly-devlog"
license = "MIT"
licenselink = "https://github.com/malespiaut/hugo-weekly-devlog/blob/master/LICENSE.md"
description = "Minimal Hugo theme, based on xmin, inspired by the old “weekly-am2” blog from SEGA AM2."
homepage = "https://github.com/malespiaut/hugo-weekly-devlog"
tags = ["minimal", "blog", "personal", "corporate", "clean", "simple", "starter", "minimalist", "retro"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Marc-Alexandre Espiaut"
  homepage = "https://espiaut.fr/marc-alexandre"
